#!/usr/bin/env bash
#######################################################
###  GitHub
#######################################################

###
### github.com
###
Host github.com
    HostName github.com
    User mtakacs
    IdentityFile ~/.ssh/keystore/github_mtakacs_rsa_2019.pem

