#!/usr/bin/env bash
#######################################################
###  Pertino: Home network access
#######################################################

Host pertino.17 p.17
    HostName readynas516.fn6hb1.pertino.net
    User tak
    IdentityFile /Users/TAKMA07/.ssh/keystore/taknet_tak.pem
Host taknet.55 t.55
    HostName 192.168.2.55
    User root
    IdentityFile /Users/TAKMA07/.ssh/keystore/taknet_tak.pem
