#!/usr/bin/env bash
#######################################################
###  Project68 Config
#######################################################

#Host *%proxy
#    ProxyCommand ssh bastion "nc -w1 $(echo %h | cut -d%% -f1) 22"
#    ForwardAgent yes
#    StrictHostKeyChecking no

Host bastion.p68
    #HostName 54.186.59.152
    HostName 52.27.70.206
    User ec2-user
    IdentityFile ~/.ssh/keystore/p68-bastion-ssh-key.pem
