#!/usr/bin/env bash
#######################################################
###  Taknet: Home network
#######################################################

Host 192.168.2.* shell.project68.com
    User tak
    IdentityFile ~/.ssh/keystore/taknet_tak.pem
Host taknet.15 t.15
    HostName 192.168.2.15
    User root
    IdentityFile ~/.ssh/keystore/taknet_tak.pem
Host taknet.16 t.16
    HostName 192.168.2.16
    User root
    IdentityFile ~/.ssh/keystore/taknet_tak.pem
Host taknet.17 t.17
    HostName 192.168.2.17
    User root
    IdentityFile ~/.ssh/keystore/taknet_tak.pem
Host taknet.18 t.18
    HostName 192.168.2.18
    User root
    IdentityFile ~/.ssh/keystore/taknet_tak.pem
