#!/usr/bin/env bash

#######################################################
## Global defaults, All the above values "stick" first,
## So these only apply if nothing else already matched.
##
## Match - @see https://raymii.org/s/tutorials/Limit_access_to_openssh_features_with_the_Match_keyword.html
#######################################################

Host *
    ForwardAgent yes
    PermitLocalCommand yes
    ServerAliveInterval 120
    Compression yes
    VisualHostKey yes
    StrictHostKeyChecking no
    GSSAPIAuthentication no
    GSSAPIDelegateCredentials no
    LocalCommand /opt/homebrew/bin/terminal-notifier -title "SSH Connection" -subtitle "%n" -message "ssh -l %r %h"
   	User mtakacs
   	Include /usr/local/etc/ssh_config

# eof
