#!/bin/bash
#  -*- shell-script -*-
#######################################################
## $Id: .bash_func,v 1.2 2008/02/15 22:10:56 tak Exp $
## Tak Config
#######################################################

##
## Mac Growl alert
## As seen on http://damonparker.org/blog/2006/11/13/iterm-and-growl/
##
growl() {
    echo -e $'\e]9;'${1}'\007';
    return ;
}

pskill(){
    local pid
    #pid=$(ps -ax | grep $1 | grep -v grep | gawk '{ print $1 }')
    pid=$(ps -ax | grep $1 | grep -v grep | awk '{ print $1 }')
    echo -n "killing $1 (process $pid)..."
    kill -9 $pid
    echo "slaughtered."
}


#####
# see who's grapping a certain port
#####
function pslisten {
        echo `lsof -n -i4TCP:$1 | grep LISTEN`
}

#################################
# Are in a git root? show branch
# @web http://www.jroller.com/melix/entry/my_git_tweaks_for_daily
#################################

## As an example
simple_git_branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ \1/'
}

parse_git_branch() {
  export repo=`git remote show -n origin 2> /dev/null | sed -e '/^  [^F]/d' -e'/remote/d' -e 's/.*\/\(.*\).git/\1/'`
  export branch=`git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'`
  echo "(${repo}::${branch})"
}
